### PR TITLE
Task #1 Implement Python script to build frequency diagram

### PR DESCRIPTION
**Pull request by zuoqin**

### CODE REVIEW

**Comment by zuoqin** [comment]
漂亮分布图刚出来了：

Figure_1

**Comment by zuoqin** [comment]
[eclipse/deeplearning4j](https://github.com/eclipse/deeplearning4j)
eclipse___deeplearning4j



[TheAlgorithms/Java](https://github.com/TheAlgorithms/Java)

TheAlgorithms__Java




**facebook/duckling:**


facebook______duckling


**ring-clojure/ring:**


ring-clojure_______ring


**andygrunwald/go-jira:**

andygrunwald_____go-jira2

**web3j/web3j:**

web3j______web3j2



**yegor256/cactoos:**

yegor256_____cactoos2

**Comment by yegor256** [comment]
@zuoqin `__pycache__` must be in `.gitignore`

**Comment by yegor256** [comment]
@zuoqin no need, we'll use Ruby (fixed in master already)

**Pull request closed without merging**
